server:
    port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/springboottest?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: admin
#    max file size for uploadinh
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
ip: localhost